name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Quantumm.Image/Quantumm.Image.csproj
      
      - name: Build
        run: dotnet build Quantumm.Image/Quantumm.Image.csproj -c Release --no-restore
      
      - name: Pack NuGet package
        run: dotnet pack Quantumm.Image/Quantumm.Image.csproj -c Release --no-build -o ./artifacts

      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
